# Generated by Django 4.0.4 on 2022-11-26 11:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='text')),
                ('date', models.DateField(default=datetime.datetime(2022, 11, 26, 11, 6, 34, 301810))),
                ('seen', models.BooleanField(default=False)),
            ],
        ),
    ]
