# Generated by Django 4.0.4 on 2022-11-26 11:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmessage',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 26, 11, 7, 26, 825599, tzinfo=utc)),
        ),
    ]
