# Generated by Django 4.0.4 on 2022-11-26 11:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_studentmessage_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmessage',
            name='student_id',
            field=models.TextField(default='', verbose_name='student_id'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentmessage',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 26, 11, 36, 44, 74215, tzinfo=utc)),
        ),
    ]
