# Generated by Django 4.0.4 on 2022-11-26 13:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_studentmessage_student_id_alter_studentmessage_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmessage',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 11, 26, 13, 59, 22, 205233, tzinfo=utc)),
        ),
    ]
